import { z } from "zod";

const positiveIntegerSchema = z
  .number()
  .int()
  .positive()
  .describe("Positive integer loop count or safety cap.");

const agentArgValueSchema = z
  .union([z.string(), z.boolean()])
  .describe(
    "Agent flag value. true renders as --flag, false omits it, strings render as --flag value.",
  );

export const recipeAgentArgsSchema = z
  .record(z.string().min(1), agentArgValueSchema)
  .describe("Per-step agent CLI flags keyed without leading dashes.");

const stepModifiers = {
  until: z.string().min(1).optional().describe("Exit condition for an until-loop."),
  repeat: positiveIntegerSchema.optional().describe("Run this step exactly this many times."),
  max: positiveIntegerSchema
    .optional()
    .describe("Maximum iterations for an until-loop safety cap."),
  args: recipeAgentArgsSchema.optional().describe("Agent flags for this step."),
} as const;

export const recipeNameSchema = z
  .string()
  .min(1)
  .regex(/^[A-Za-z0-9_-]+$/, "Use only letters, numbers, '_' or '-'.")
  .describe("Recipe name. It maps to <name>.yaml in a recipes directory.");

export const recipeArgumentNameSchema = z
  .string()
  .min(1)
  .regex(/^[A-Za-z_][A-Za-z0-9_]*$/, "Use a shell-safe identifier like plan or plan_file.")
  .describe("Argument name used as --<name>, {{name}}, $NAME, or ${NAME}.");

export const recipeArgumentTypeSchema = z
  .enum(["string", "path", "file", "directory", "integer", "number", "boolean"])
  .default("string")
  .describe("Argument type and validation rule.");

export const recipeArgumentSchema = z
  .object({
    name: recipeArgumentNameSchema,
    description: z.string().min(1).optional().describe("Human-readable argument description."),
    type: recipeArgumentTypeSchema,
    required: z.boolean().default(true).describe("Whether the caller must provide this argument."),
    default: z
      .union([z.string(), z.number(), z.boolean()])
      .optional()
      .describe("Default value used when the caller omits this argument."),
    choices: z
      .array(z.string().min(1))
      .min(1)
      .optional()
      .describe("Allowed string values after type coercion."),
    pattern: z.string().min(1).optional().describe("Regular expression the value must match."),
  })
  .strict()
  .superRefine((arg, ctx) => {
    if (arg.pattern) {
      try {
        new RegExp(arg.pattern);
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        ctx.addIssue({ code: "custom", path: ["pattern"], message: `Invalid regex: ${message}` });
      }
    }

    if (arg.default === undefined) return;
    if (!defaultValueMatchesType(arg.default, arg.type)) {
      ctx.addIssue({
        code: "custom",
        path: ["default"],
        message: `Default value does not match type "${arg.type}".`,
      });
    }
  })
  .describe("Recipe argument definition.");

export const recipeTaskStepSchema = z
  .object({
    task: z.string().min(1).describe("Task prompt template."),
    ...stepModifiers,
  })
  .strict()
  .describe("Single task step.");

export const recipeGroupStepSchema = z
  .object({
    tasks: z.array(z.string().min(1)).min(1).describe("Task prompt templates in a group."),
    ...stepModifiers,
  })
  .strict()
  .describe("Grouped task step.");

export const recipeStepSchema = z
  .union([recipeTaskStepSchema, recipeGroupStepSchema])
  .superRefine((step, ctx) => {
    if (step.repeat !== undefined && step.until !== undefined) {
      ctx.addIssue({
        code: "custom",
        path: ["repeat"],
        message:
          "repeat and until cannot be combined. Use repeat for a fixed count or until for a condition.",
      });
    }
    if (step.repeat !== undefined && step.max !== undefined) {
      ctx.addIssue({
        code: "custom",
        path: ["max"],
        message: "repeat and max cannot be combined. repeat already specifies an exact count.",
      });
    }
    if (step.max !== undefined && step.until === undefined) {
      ctx.addIssue({
        code: "custom",
        path: ["max"],
        message: "max can only be used with until. It acts as a safety cap for until-loops.",
      });
    }
  })
  .describe(
    "Recipe step. Supports the same task, group, until, repeat, max, and args features as CLI steps.",
  );

export const recipeFileSchema = z
  .object({
    description: z.string().min(1).optional().describe("Human-readable recipe description."),
    arguments: z
      .array(recipeArgumentSchema)
      .default([])
      .describe("Arguments accepted by this recipe."),
    steps: z.array(recipeStepSchema).min(1).describe("Steps generated by this recipe."),
  })
  .strict()
  .superRefine((recipe, ctx) => {
    const seen = new Map<string, number>();
    recipe.arguments.forEach((argument, index) => {
      const previous = seen.get(argument.name);
      if (previous !== undefined) {
        ctx.addIssue({
          code: "custom",
          path: ["arguments", index, "name"],
          message: `Duplicate argument name "${argument.name}". First defined at arguments.${previous}.name.`,
        });
      }
      seen.set(argument.name, index);
    });
  })
  .describe("Loop recipe file. YAML is parsed, then this Zod schema validates it.");

function defaultValueMatchesType(
  value: string | number | boolean,
  type: RecipeArgumentType,
): boolean {
  switch (type) {
    case "string":
    case "path":
    case "file":
    case "directory":
      return typeof value === "string";
    case "integer":
      return typeof value === "number" && Number.isInteger(value);
    case "number":
      return typeof value === "number" && Number.isFinite(value);
    case "boolean":
      return typeof value === "boolean";
  }
}

export type RecipeArgumentType = z.infer<typeof recipeArgumentTypeSchema>;
export type RecipeArgument = z.infer<typeof recipeArgumentSchema>;
export type RecipeArgumentValue = string | number | boolean;
export type RecipeStepFile = z.infer<typeof recipeStepSchema>;
export type RecipeFile = z.infer<typeof recipeFileSchema>;
